<?php

namespace Database\Seeders;

use App\Models\Destination;
use Illuminate\Database\Seeder;

class DestinationSeeder extends Seeder
{
    public function run(): void
    {
        $destinations = [
            // ==================== BEACHES ====================
            [
                'name' => 'Sidi Abdelaziz',
                'description' => 'Plage autorisée à la baignade, daïra de Chekfa, wilaya de Jijel.',
                'address' => 'Sidi Abdelaziz',
                'latitude' => 36.853261,
                'longitude' => 6.051473,
                'category' => 'beach',
                'tags' => ['beach', 'swimming', 'jijel', 'chekfa'],
            ],
            [
                'name' => 'Rocher Noir',
                'description' => 'Plage autorisée à la baignade, daïra de El Aouana, wilaya de Jijel.',
                'address' => 'El Aouana',
                'latitude' => 36.7870251,
                'longitude' => 5.651271,
                'category' => 'beach',
                'tags' => ['beach', 'swimming', 'jijel', 'el_aouana'],
            ],
            [
                'name' => 'Beni belaid',
                'description' => 'Plage autorisée à la baignade, daïra de El Ancer, wilaya de Jijel.',
                'address' => 'Kheiri Oued Adjoul',
                'latitude' => 36.8849,
                'longitude' => 6.1392,
                'category' => 'beach',
                'tags' => ['beach', 'swimming', 'jijel', 'el_ancer'],
            ],
            [
                'name' => 'Kotama',
                'description' => 'Plage autorisée à la baignade, daïra de Jijel, wilaya de Jijel.',
                'address' => 'Jijel centre-ville',
                'latitude' => 36.8117,
                'longitude' => 5.773,
                'category' => 'beach',
                'tags' => ['beach', 'swimming', 'jijel', 'jijel_centre'],
            ],
            [
                'name' => 'Grand Phare',
                'description' => 'Plage autorisée à la baignade, daïra de Jijel, wilaya de Jijel.',
                'address' => 'Jijel',
                'latitude' => 36.8166,
                'longitude' => 5.7666,
                'category' => 'beach',
                'tags' => ['beach', 'swimming', 'jijel', 'jijel_centre'],
            ],
            [
                'name' => 'Bazoul',
                'description' => 'Plage autorisée à la baignade, daïra de Taher, wilaya de Jijel.',
                'address' => 'Taher',
                'latitude' => 36.82329,
                'longitude' => 5.907,
                'category' => 'beach',
                'tags' => ['beach', 'swimming', 'jijel', 'taher'],
            ],
            [
                'name' => 'Aftis',
                'description' => 'Plage autorisée à la baignade, daïra de El Aouana, wilaya de Jijel.',
                'address' => 'El Aouana',
                'latitude' => 36.714,
                'longitude' => 5.550,
                'category' => 'beach',
                'tags' => ['beach', 'swimming', 'jijel', 'el_aouana'],
            ],
            [
                'name' => 'Bordj Blida',
                'description' => 'Plage autorisée à la baignade, daïra de El Aouana, wilaya de Jijel.',
                'address' => 'El Aouana',
                'latitude' => 36.79301,
                'longitude' => 5.654,
                'category' => 'beach',
                'tags' => ['beach', 'swimming', 'jijel', 'el_aouana'],
            ],
            [
                'name' => 'chalate',
                'description' => 'Plage autorisée à la baignade, daïra de El Aouana, wilaya de Jijel.',
                'address' => 'El Aouana',
                'latitude' => 36.7589,
                'longitude' => 5.5448,
                'category' => 'beach',
                'tags' => ['beach', 'swimming', 'jijel', 'el_aouana'],
            ],
            [
                'name' => 'Ouled Bounnar',
                'description' => 'Plage autorisée à la baignade, daïra de Jijel, wilaya de Jijel.',
                'address' => 'Jijel',
                'latitude' => 36.81922,
                'longitude' => 5.71293,
                'category' => 'beach',
                'tags' => ['beach', 'swimming', 'jijel', 'jijel_centre'],
            ],
            [
                'name' => 'La crique',
                'description' => 'Plage autorisée à la baignade, daïra de Jijel, wilaya de Jijel.',
                'address' => 'Jijel',
                'latitude' => 36.81849,
                'longitude' => 5.70538,
                'category' => 'beach',
                'tags' => ['beach', 'swimming', 'jijel', 'jijel_centre'],
            ],
            [
                'name' => 'El Aouana Centre',
                'description' => 'Plage autorisée à la baignade, daïra de El Aouana, wilaya de Jijel.',
                'address' => 'El Aouana',
                'latitude' => 36.77676,
                'longitude' => 5.6102,
                'category' => 'beach',
                'tags' => ['beach', 'swimming', 'jijel', 'el_aouana'],
            ],
            [
                'name' => 'Aouka',
                'description' => 'Plage autorisée à la baignade, daïra de Jijel, wilaya de Jijel.',
                'address' => 'Jijel centre-ville',
                'latitude' => 36.78442,
                'longitude' => 5.97236,
                'category' => 'beach',
                'tags' => ['beach', 'swimming', 'jijel', 'jijel_centre'],
            ],
            [
                'name' => 'Terre rouge',
                'description' => 'Plage autorisée à la baignade, daïra de Jijel, wilaya de Jijel.',
                'address' => 'Jijel',
                'latitude' => 36.8000,
                'longitude' => 5.7667,
                'category' => 'beach',
                'tags' => ['beach', 'swimming', 'jijel', 'jijel_centre'],
            ],
            [
                'name' => 'El Bordj',
                'description' => 'Plage autorisée à la baignade, daïra de Taher, wilaya de Jijel.',
                'address' => 'Emir Abdel Kader',
                'latitude' => null,
                'longitude' => null,
                'category' => 'beach',
                'tags' => ['beach', 'swimming', 'jijel', 'taher'],
            ],
            [
                'name' => 'Rocher aux moules',
                'description' => 'Plage autorisée à la baignade, daïra de Chekfa, wilaya de Jijel.',
                'address' => 'Sidi Abdelaziz',
                'latitude' => 36.86437,
                'longitude' => 6.06860,
                'category' => 'beach',
                'tags' => ['beach', 'swimming', 'jijel', 'chekfa'],
            ],
            [
                'name' => 'El M\'Zair',
                'description' => 'Plage autorisée à la baignade, daïra de Chekfa, wilaya de Jijel.',
                'address' => 'El Kennar',
                'latitude' => 36.8058,
                'longitude' => 5.9287,
                'category' => 'beach',
                'tags' => ['beach', 'swimming', 'jijel', 'chekfa'],
            ],
            [
                'name' => 'El Kennar',
                'description' => 'Plage autorisée à la baignade, daïra de Chekfa, wilaya de Jijel.',
                'address' => 'El Kennar',
                'latitude' => 36.82472,
                'longitude' => 5.95907,
                'category' => 'beach',
                'tags' => ['beach', 'swimming', 'jijel', 'chekfa'],
            ],
            [
                'name' => 'Tasakch',
                'description' => 'Plage autorisée à la baignade, daïra de El Ancer, wilaya de Jijel.',
                'address' => 'Kheiri Oued Adjoul',
                'latitude' => 36.89,
                'longitude' => 6.14,
                'category' => 'beach',
                'tags' => ['beach', 'swimming', 'jijel', 'el_ancer'],
            ],
            [
                'name' => 'Kissir',
                'description' => 'Plage autorisée à la baignade, daïra de El Aouana, wilaya de Jijel.',
                'address' => 'El Aouana',
                'latitude' => 36.79769,
                'longitude' => 5.67398,
                'category' => 'beach',
                'tags' => ['beach', 'swimming', 'jijel', 'el_aouana'],
            ],
            [
                'name' => 'Timdiouane',
                'description' => 'Plage autorisée à la baignade, daïra de Chekfa, wilaya de Jijel.',
                'address' => 'Sidi Abdelaziz',
                'latitude' => 36.7842,
                'longitude' => 5.9083,
                'category' => 'beach',
                'tags' => ['beach', 'swimming', 'jijel', 'chekfa'],
            ],
            [
                'name' => 'El Oueldja',
                'description' => 'Plage autorisée à la baignade, daïra de Ziama Mansouriah, wilaya de Jijel.',
                'address' => 'Ziama Mansouriah',
                'latitude' => 36.6632,
                'longitude' => 5.461399,
                'category' => 'beach',
                'tags' => ['beach', 'swimming', 'jijel', 'ziama_mansouriah'],
            ],
            [
                'name' => 'TAZA',
                'description' => 'Plage autorisée à la baignade, daïra de Ziama Mansouriah, wilaya de Jijel.',
                'address' => 'Ziama Mansouriah',
                'latitude' => 36.7078,
                'longitude' => 5.54176,
                'category' => 'beach',
                'tags' => ['beach', 'swimming', 'jijel', 'ziama_mansouriah'],
            ],
            [
                'name' => 'Marsidi',
                'description' => 'Plage autorisée à la baignade, daïra de Ziama Mansouriah, wilaya de Jijel.',
                'address' => 'Ziama Mansouriah',
                'latitude' => 36.6639,
                'longitude' => 5.45904,
                'category' => 'beach',
                'tags' => ['beach', 'swimming', 'jijel', 'ziama_mansouriah'],
            ],
            [
                'name' => 'Rouge',
                'description' => 'Plage autorisée à la baignade, daïra de Ziama Mansouriah, wilaya de Jijel.',
                'address' => 'Ziama Mansouriah',
                'latitude' => 36.6575,
                'longitude' => 5.4336,
                'category' => 'beach',
                'tags' => ['beach', 'swimming', 'jijel', 'ziama_mansouriah'],
            ],
            [
                'name' => 'Boulekhmass',
                'description' => 'Plage autorisée à la baignade, daïra de Ziama Mansouriah, wilaya de Jijel.',
                'address' => 'Ziama Mansouriah',
                'latitude' => 36.6575,
                'longitude' => 5.4542,
                'category' => 'beach',
                'tags' => ['beach', 'swimming', 'jijel', 'ziama_mansouriah'],
            ],
            [
                'name' => 'Les Grottes Merveilleuses',
                'description' => 'Plage autorisée à la baignade, daïra de Ziama Mansouriah, wilaya de Jijel.',
                'address' => 'Ziama Mansouriah',
                'latitude' => 36.69599,
                'longitude' => 5.52741,
                'category' => 'beach',
                'tags' => ['beach', 'swimming', 'jijel', 'ziama_mansouriah'],
            ],

            // ==================== NATURE SPOTS ====================
            [
                'name' => 'Guerrouche',
                'description' => 'La Forêt de Grouch, daïra de El Aouana, wilaya de Jijel.',
                'address' => 'El Aouana',
                'latitude' => 36.7,
                'longitude' => 5.61667,
                'category' => 'nature',
                'tags' => ['forest', 'nature', 'jijel', 'el_aouana'],
            ],
            [
                'name' => 'Bouafroun',
                'description' => 'La Forêt de Bouafroun, daïra de djimla, wilaya de Jijel.',
                'address' => 'Djimla',
                'latitude' => 36.5801,
                'longitude' => 5.8843,
                'category' => 'nature',
                'tags' => ['forest', 'nature', 'jijel', 'djimla'],
            ],
            [
                'name' => 'El Ma El Bared',
                'description' => 'La Forêt El Ma El Bared, daïra de Texenna, wilaya de Jijel.',
                'address' => 'Texenna',
                'latitude' => 36.63637,
                'longitude' => 5.71035,
                'category' => 'nature',
                'tags' => ['forest', 'nature', 'jijel', 'texenna'],
            ],
            [
                'name' => 'Bouhenche',
                'description' => 'La Forêt El Ma El Bared, daïra de Texenna, wilaya de Jijel.',
                'address' => 'Texenna',
                'latitude' => 36.77100,
                'longitude' => 5.813,
                'category' => 'nature',
                'tags' => ['forest', 'nature', 'jijel', 'texenna'],
            ],
            [
                'name' => 'Beni Fergane',
                'description' => 'La Forêt El Ma El Bared, daïra d\'El Milia, wilaya de Jijel.',
                'address' => 'El Milia',
                'latitude' => 36.75000,
                'longitude' => 5.9500,
                'category' => 'nature',
                'tags' => ['forest', 'nature', 'jijel', 'el_milia'],
            ],
            [
                'name' => 'Bou Azza',
                'description' => 'Djebel Sidi BouAzza (Commune de Djimla, wilaya de Jijel) est un pic et a une altitude de 1 520 mètres. Djebel Sidi Bou Azza se trouve à proximité de la localité de Bouafroun, ainsi que du village de Mechtat Berraka.',
                'address' => 'Djimla',
                'latitude' => 36.6046,
                'longitude' => 5.92205,
                'category' => 'nature',
                'tags' => ['mountain', 'nature', 'jijel', 'djimla'],
            ],
            [
                'name' => 'Seddet',
                'description' => 'Djebel Seddet (Bordj Taher, Chekfa, wilaya de Jijel) est une montagne et a une altitude de 843 mètres. Djebel Seddet se trouve à proximité de la localité de Mechta Afouzâr, ainsi que de Dechra Takhnâk',
                'address' => 'Bordj T\'har',
                'latitude' => 36.78659,
                'longitude' => 6.03245,
                'category' => 'nature',
                'tags' => ['mountain', 'nature', 'jijel', 'chekfa'],
            ],
            [
                'name' => 'Tamentout',
                'description' => 'Col de Tamentout (Commune de Djimla, wilaya de Jijel) est une selle. Col de Tamentout se trouve à proximité du village de Taous, ainsi que de Souk el Hed.',
                'address' => 'Djimla',
                'latitude' => 36.5499,
                'longitude' => 5.8452,
                'category' => 'nature',
                'tags' => ['mountain_pass', 'nature', 'jijel', 'djimla'],
            ],
            [
                'name' => 'Boulhadaid',
                'description' => 'La Cascade Boulhadaid est un joyau naturel caché situé dans la commune d\'El Anser, dans la wilaya de Jijel. Nichée au cœur d\'un environnement montagneux luxuriant et préservé, cette chute d\'eau offre une véritable halte de fraîcheur loin de l\'agitation des zones côtières.',
                'address' => 'El Ancer',
                'latitude' => 36.7860,
                'longitude' => 5.9926,
                'category' => 'nature',
                'tags' => ['waterfall', 'nature', 'jijel', 'el_ancer'],
            ],
            [
                'name' => 'Mozenkok',
                'description' => 'La cascade de Mouzenkouk (aussi orthographiée Mozankok ou Mouzengoug) un joyau naturel prisé en période de chaleur. Elle est nichée dans le village d\'Aït Ali, sur les hauteurs de Ziama Mansouriah.',
                'address' => 'Ziama Mansouriah',
                'latitude' => 36.673,
                'longitude' => 5.481,
                'category' => 'nature',
                'tags' => ['waterfall', 'nature', 'jijel', 'ziama_mansouriah'],
            ],
            [
                'name' => 'El Mizaba',
                'description' => 'Le chute d\'eau de Mizaba, situées dans la région de Tazmourt à Texenna (wilaya de Jijel), offrent un cadre naturel exceptionnel au cœur des montagnes. Ce joyau caché, accessible depuis les hauteurs de Texenna',
                'address' => 'Texenna',
                'latitude' => 36.60317,
                'longitude' => 5.71481,
                'category' => 'nature',
                'tags' => ['waterfall', 'nature', 'jijel', 'texenna'],
            ],
            [
                'name' => 'Trakcht',
                'description' => 'La cascade de Trakcht (ou Trakachat), également appelée "chalet du Sahel" ou "chute des Chaabna", est située dans la localité de Trakcht, dans la commune et daïra de Texenna',
                'address' => 'Texenna',
                'latitude' => 36.6606,
                'longitude' => 5.79098,
                'category' => 'nature',
                'tags' => ['waterfall', 'nature', 'jijel', 'texenna'],
            ],
            [
                'name' => 'El Machaki',
                'description' => 'Aïn El Mechaki, Situé à 62 Km du chef lieu de la Wilaya et de 05 Km de la commune de Selma Ben Ziada, non loin des grottes "la Madeleine", à 900 m de la route nationale, ce ruisseau se trouve sur le piémont et s\'écoule à intervalles réguliers: le phénomène de ruissellement dont l\'explication n\'a pas été élucidée a ce jour, dure 10 mn, s\'interrompt pendant 40 mn et se répète quotidiennement durant l\'année. C\'est une eau pure et propre à la consommation. De là, résulte le fait que le site est fréquenté par beaucoup de personnes en quête d\'un lieu paisible susceptible de leur apporter force et guérison.',
                'address' => 'Selma Ben Ziada',
                'latitude' => 36.604145,
                'longitude' => 5.660354,
                'category' => 'nature',
                'tags' => ['spring', 'nature', 'jijel', 'selma_ben_ziada'],
            ],
            [
                'name' => 'Les Grottes Merveilleuses (Nature)',
                'description' => 'Les Grottes Merveilleuses : Située entre el aouanna et Ziama Mansourieh, à 35 km à l\'ouest de Jijel, elle a été découverte en 1917 lors de l\'ouverture de la route nationale n°43. Considéré comme l\'une des merveilles de la nature en termes de forme et sculpture faites par les stalagmites et les stalactites. La grotte merveilleuse contient des formes étranges incarnées dans la nature à travers le monde, comme le palais du Kremlin en Russie, la tour de Pise, la statue de la liberté en Amérique, la coupe du monde et beaucoup d\'autres formes, plus de merveilleux sons musicaux qui ajoutent à l\'atmosphère plus de plaisir. Parmi les particularités de cette grotte également, sa température constante tout au long de l\'année (18°), tandis que l\'humidité est estimée à 60 degrés et plus',
                'address' => 'Ziama Mansouriah',
                'latitude' => 36.6827,
                'longitude' => 5.5183,
                'category' => 'nature',
                'tags' => ['cave', 'nature', 'jijel', 'ziama_mansouriah'],
            ],
            [
                'name' => 'Ghar El Baz',
                'description' => 'Ghar El Baz : Un site préhistorique, qui est une grande grotte ouverte sur la route à Ziama Mansouriah. Dans cette grotte, on trouve une grande salle de 50 m de large, 60 m de large et 20 à 32 mètres de hauteur du côté sud de la salle, où il y a une embrasure s\'est élargie à cause de la corrosion. La température dans la grotte est estimée à 16 degrés, mais elle diffère des grottes merveilleuses par l\'absence de stalagmites et stalactites. Elle rester une autre attraction touristique de la capitale de la Corniche.',
                'address' => 'Ziama Mansouriah',
                'latitude' => 36.70053,
                'longitude' => 5.5379,
                'category' => 'nature',
                'tags' => ['cave', 'nature', 'prehistoric', 'jijel', 'ziama_mansouriah'],
            ],
            [
                'name' => 'Parc animalier',
                'description' => 'ZOO : Ce Parc a été créé en 2006 à Kissir commune d\'El Aouana, il s\'étend sur une superficie de 25 Ha, il abrite plusieurs espèces de mammifères ainsi que des volières d\'oiseaux, il constitue un espace de loisir et de détente aux citoyens.',
                'address' => 'El Aouana',
                'latitude' => 36.79039,
                'longitude' => 5.66319,
                'category' => 'nature',
                'tags' => ['zoo', 'nature', 'jijel', 'el_aouana'],
            ],
            [
                'name' => 'Le parc National de Taza',
                'description' => 'réserve naturelle : Le parc est inclus dans le réseau mondial des réserves de la biosphère de l\'Unesco. Il renferme des écosystèmes marin et terrestre au niveau desquels on dénombre plusieurs espèces végétales protégées par la loi. La faune y est aussi importante comme le singe Magot espèce rare et endémique à l\'Afrique du Nord.',
                'address' => 'Ziama Mansouriah',
                'latitude' => 36.6923,
                'longitude' => 5.5863,
                'category' => 'nature',
                'tags' => ['national_park', 'nature', 'unesco', 'jijel', 'ziama_mansouriah'],
            ],
            [
                'name' => 'La Réserve naturelle de Beni Belaïd',
                'description' => 'réserve naturelle : Inscrite sur la liste des zones humides d\'importance internationale, le lac de Beni Belaïd couvre une superficie de 600 hectares. Le site abrite une faune rare et particulière notamment la présence d\'une avifaune riche et diversifiée comprenant plusieurs espèces rares comme L\'Aythya nyroca, L\'Alcedo atthis, Le Porphyrio porphirio',
                'address' => 'Beni Belaïd',
                'latitude' => 36.8722,
                'longitude' => 6.1026,
                'category' => 'nature',
                'tags' => ['nature_reserve', 'lake', 'nature', 'jijel', 'beni_belaid'],
            ],
            [
                'name' => 'Lac Tamesguida',
                'description' => 'Lac de Tamesguida (aussi appelé Ghdir Oum Lehnache ou lac des serpents) est situé sur les hauteurs de la commune de Béni Yadjis, dans la wilaya de Jijel',
                'address' => 'Ben Yadjis',
                'latitude' => 36.5658,
                'longitude' => 5.7032,
                'category' => 'nature',
                'tags' => ['lake', 'nature', 'jijel', 'ben_yadjis'],
            ],
            [
                'name' => 'L\'île El Aouana',
                'description' => 'l\'île des rêves est également appelée l\'île de la mer Méditerranée, à seulement 950 mètres de la plage, d\'une superficie de 06 hectares, mandat de El Aouana de Jijel.',
                'address' => 'El Aouana Centre',
                'latitude' => 36.78541,
                'longitude' => 5.60852,
                'category' => 'nature',
                'tags' => ['island', 'nature', 'jijel', 'el_aouana'],
            ],
            [
                'name' => 'L\'île de Borj Blida',
                'description' => 'île Andrew : petite île rocheuse (d\'une superficie d\'environ 4 hectares) fait face au littoral et à la plage de Bordj Blida, à mi-chemin entre le centre-ville de Jijel et la ville d\'El Aouana',
                'address' => 'Borj Blida (Andrew)',
                'latitude' => 36.79472,
                'longitude' => 5.55083,
                'category' => 'nature',
                'tags' => ['island', 'nature', 'jijel', 'el_aouana'],
            ],
            [
                'name' => 'Barrage Erraguene',
                'description' => 'Barrage Erraguene : Situé sur les hauteurs de la commune d\'Erraguene Souissi rattachée administrativement à la daïra de Ziama Mansouriah, se trouvant entre les wilayas de Sétif et Jijel, érigé en 1961, il est actuellement le pôle d\'attraction des touristes et visiteurs notamment ceux qui sont friands pour le tourisme de montagne et les sports nautiques.',
                'address' => 'Erraguene Souissi',
                'latitude' => 36.58185,
                'longitude' => 5.57677,
                'category' => 'nature',
                'tags' => ['dam', 'nature', 'jijel', 'erraguene_souissi'],
            ],
            [
                'name' => 'Le Port de Jijel',
                'description' => 'Port de Djen Djen : est le plus grand port en Algérie et se place parmi les plus grandes œuvres portuaires en Méditerranée. Situé dans la Wilaya de Jijel à l\'Est de l\'Algérie, il bénéficie d\'une place stratégique à moins de 50 miles de la route maritime reliant le canal de Suez au détroit de Gibraltar, cette position lui confère un rôle privilégié, s\'étend sur une superficie de 210 hectares, avec un tirant d\'eau allant jusqu\'à -18,20m',
                'address' => 'Jijel',
                'latitude' => 36.82236,
                'longitude' => 5.88833,
                'category' => 'nature',
                'tags' => ['port', 'nature', 'jijel', 'jijel_centre'],
            ],
            [
                'name' => "Port d'El Aouana",
                'description' => 'Port de pêche et de plaisance constitué par deux jetées de protection en enrochement et une jetée centrale de protection.',
                'address' => 'El Aouana Centre',
                'latitude' => 36.77716,
                'longitude' => 5.60435,
                'category' => 'nature',
                'tags' => ['port', 'nature', 'jijel', 'el_aouana'],
            ],
            [
                'name' => 'Le Port de ziama mansouriah',
                'description' => "Le port de pêche et de plaisance de Ziama Mansouriah, situé à l'ouest de la wilaya de Jijel",
                'address' => 'Ziama Mansouriah',
                'latitude' => 36.67700,
                'longitude' => 5.47929,
                'category' => 'nature',
                'tags' => ['port', 'nature', 'jijel', 'ziama_mansouriah'],
            ],

            // ==================== HISTORICAL SITES ====================
            [
                'name' => 'Placette du Conjador',
                'description' => 'La Statue du Pêcheur (Conjador) ou la Statue de la Liberté de la capitale de la Corniche, comme certains aiment l\'appeler, est l\'un des symboles historiques qui témoignent tous les événements dont la ville a été témoin depuis. Fut construite immédiatement après le tremblement de terre de 1856, qui frappa la région de Jijel et y détruisit tout, par le sculpteur italien Guglielmi en 1888 dans une usine de plomberie dont le nom est encore gravé sur l\'une des parties de cette statue située sur la place de la république qui l\'entoure de l\'Ouest, le vieux port de pêche au Nord, la grande fontaine de Jijel au Sud, et le siège de la commune de Jijel de l\'Est.',
                'address' => 'Jijel',
                'latitude' => 36.825159,
                'longitude' => 5.767655,
                'category' => 'historical',
                'tags' => ['statue', 'historical', 'jijel', 'jijel_centre'],
            ],
            [
                'name' => 'Grand Phare (Historical)',
                'description' => 'Le phare de Ras El Afia (Grand Phare), le gardien vigilant de la Corniche, est situé au sommet de Ras El Afia, à 500 m dans la mer, à partir de la plage qui a le même nom, à 06 km à l\'ouest de Jijel. C\'est l\'une des plus grandes et des plus anciennes des 24 balises du littoral algérien. Elle a été construite par le sculpteur français Charles Salva en 1867 au sommet du "Grifat" à l\'aide d\'une sorte de pierre locale de couleur bleue, et il a été mise en marche en 1907 avec du diesel, il a été alimenté à l\'électricité depuis de 1936 ensuite à partir de 1992 son exécution est devenu automatique.',
                'address' => 'Jijel',
                'latitude' => 36.7989,
                'longitude' => 5.7315,
                'category' => 'historical',
                'tags' => ['lighthouse', 'historical', 'jijel', 'jijel_centre'],
            ],
            [
                'name' => 'Bateau Baba Arroudj',
                'description' => 'Bateau Baba Arroudj : A côté de l\'hôtel Kotama au centre-ville de Jijel, se situe le bateau de Baba Aroudj, conçu dans un style traditionnel datant du 15ème siècle, fait de cuivre et de bronze. ce qui a ajouté à son la beauté et la splendeur étaient la fontaine qui coule périodiquement vers les 12 rames du navire.',
                'address' => 'Jijel',
                'latitude' => 36.8163,
                'longitude' => 5.7712,
                'category' => 'historical',
                'tags' => ['monument', 'historical', 'jijel', 'jijel_centre'],
            ],
            [
                'name' => 'Cimetière Phénicien El Rabta',
                'description' => 'Coincée entre l\'anse des Béni Caïd et la plage de Boussadoune, la nécropole phénicienne de la Pointe Noire, connue des jijeliens par Rabta, est située sur une éminence en tuf battue par la mer et les vents. C\'est l\'une des plus importantes nécropoles phéniciennes de la ville de Jijel et même d\'Algérie',
                'address' => 'El Rabta',
                'latitude' => 36.81667,
                'longitude' => 5.75,
                'category' => 'historical',
                'tags' => ['cemetery', 'phoenician', 'historical', 'jijel'],
            ],
            [
                'name' => 'Mur de l\'ancienne ville',
                'description' => 'Mur de l\'ancienne ville de Beaumarche',
                'address' => 'Beaumarche',
                'latitude' => 36.8247,
                'longitude' => 5.7599,
                'category' => 'historical',
                'tags' => ['wall', 'historical', 'jijel'],
            ],
            [
                'name' => 'Cimetière des Chrétiens',
                'description' => 'Le Cimetière des Chrétiens (aussi appelé cimetière européen) de Jijel est situé à proximité du centre-ville, dominant le littoral',
                'address' => 'Jijel',
                'latitude' => 36.8172,
                'longitude' => 5.7667,
                'category' => 'historical',
                'tags' => ['cemetery', 'historical', 'jijel', 'jijel_centre'],
            ],
            [
                'name' => 'Le site archéologique de Chobae',
                'description' => 'Le site archéologique de Chobae Municipium date de la période romaine, il est composé des restes de la ville romaine qui se limite essentiellement dans la partie occidentale du mur de la ville. La ville de Chobae a été fondée par l\'empereur romain OCTAVIUS pendant le dernier quart du premier siècle avant JC.',
                'address' => 'Ziama Mansouriah',
                'latitude' => 36.6595,
                'longitude' => 5.435,
                'category' => 'historical',
                'tags' => ['archaeological', 'roman', 'historical', 'jijel', 'ziama_mansouriah'],
            ],

            // ==================== CULTURAL ATTRACTIONS ====================
            [
                'name' => 'Fabrication d’ustensiles en bois',
                'description' => 'Artisanat : Cet artisanat est répandu dans les zones de montagne comme la commune de Djimla, Emir Abdelkader et ELMilia en raison de la disponibilité de la matière première, Arbres (liège, hêtre, pin…). Ses principaux produits comprennent : plats, cuillères, bols en bois',
                'address' => 'Djimla, ELMilia',
                'latitude' => null,
                'longitude' => null,
                'category' => 'cultural',
                'tags' => ['handicraft', 'woodworking', 'cultural', 'jijel'],
            ],
            [
                'name' => 'Fabrication du cuir',
                'description' => 'Artisanat : Cette activité est particulièrement localisée dans les régions orientales de la wilaya, SIDI ABDELAZIZ et DJEMAA BENI HABIBI, est l\'un des plus anciens métiers traditionnels… Ses principaux produits comprennent: ceintures en cuir, sacs, accessoires en cuir de voyage et de chasse',
                'address' => 'Sidi Abdelaziz',
                'latitude' => null,
                'longitude' => null,
                'category' => 'cultural',
                'tags' => ['handicraft', 'leather', 'cultural', 'jijel'],
            ],
            [
                'name' => 'Poterie',
                'description' => 'Artisanat : La pratique de ce métier est confinée aux zones rurales, ça consiste principalement à la fabrication de vaisselle et objets d\'ornementation en terre cuite, poterie fine.',
                'address' => 'zones rurales',
                'latitude' => null,
                'longitude' => null,
                'category' => 'cultural',
                'tags' => ['handicraft', 'pottery', 'cultural', 'jijel'],
            ],
            [
                'name' => 'Couture de vêtement traditionnelle',
                'description' => 'Vêtement traditionnelle : Cette activité est dans la Broderie et la couture de vêtements traditionnels sur tous les types de tissus, laine, coton, poils de chameaux et de soie, les produits les plus importants sont: la couture et la décoration des foulards et des châles, Fetla, Chamsa.',
                'address' => 'Jijel',
                'latitude' => null,
                'longitude' => null,
                'category' => 'cultural',
                'tags' => ['handicraft', 'embroidery', 'traditional_clothing', 'cultural', 'jijel'],
            ],
            [
                'name' => 'Bimbelotier',
                'description' => 'Bimbelotier : Cette activité dans la wilaya a prospéré pour l\'abondance de la matière première Surtout les articles en liège, coquillages, et bois et sont souvent utilisés pour la décoration. Ses principaux produits sont les cadres, les articles à base de bois et coquillages',
                'address' => 'Jijel',
                'latitude' => null,
                'longitude' => null,
                'category' => 'cultural',
                'tags' => ['handicraft', 'decoration', 'cultural', 'jijel'],
            ],
            [
                'name' => 'Plats et gâteaux traditionnels',
                'description' => 'La gastronomie de Jijel est particulièrement réputée pour ses plats conviviaux à base de pâtes façonnées à la main et de produits du terroir. Des spécialités comme la Douida, Berkoukes, le Bouicha ou les Ghrayef célèbrent le patrimoine culinaire riche de cette région côtière du nord-est de l\'Algérie',
                'address' => 'Jijel',
                'latitude' => null,
                'longitude' => null,
                'category' => 'cultural',
                'tags' => ['cuisine', 'gastronomy', 'cultural', 'jijel'],
            ],
        ];

        foreach ($destinations as $destination) {
            Destination::updateOrCreate(
                ['name' => $destination['name']],
                [
                    'description' => $destination['description'],
                    'address' => $destination['address'],
                    'latitude' => $destination['latitude'],
                    'longitude' => $destination['longitude'],
                    'category' => $destination['category'],
                    'is_featured' => false,
                    'tags' => $destination['tags'],
                ]
            );
        }
    }
}
